flowchart TB
    subgraph Actors["Actors"]
        Person_Sobstvennik["Person_Sobstvennik"]
        Person_Predsedatel_ST["Person_Predsedatel_ST"]
        Person_Buhgalter_ST["Person_Buhgalter_ST"]
    end
