name: GitGuardian Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история для сканирования

      - name: GitGuardian Scan
        uses: GitGuardian/ggshield-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
